language: java
jdk:
  - oraclejdk8
services:
  - postgresql
cache:
  directories:
    - $HOME/.m2
install: true
before_script:
  - psql -c 'create database meetingapp;' -U postgres
  - travis_wait 45 ./mvnw install -q -U -DskipTests=true -Pfast -Dmaven.test.redirectTestOutputToFile=true